apiVersion: apps/v1

kind: Deployment

metadata:

  name: spacewellpoc

  labels:

    app: web

spec:

  replicas: 2

  selector:

    matchLabels:

      app: web

  template:

    metadata:

      labels:

        app: web

    spec:

      containers:

        - name: spacewell-app-container1-latest

          image: adrija1993/centosnew:0.0.1-SNAPSHOT

          ports:

            - containerPort: 8082