apiVersion: v1
kind: Deployment
metadata:
   name: spring-boot-app
labels:
   app: spring-boot-app
spec:
   replicas: 2
   selector:
     matchLabels:
      app: spring-boot-app
    template:
     metdata:
       labels:
         app; spring-boot-app
     spec:
       containers:
         - name: spring-boot-app
           image: adrija1993/centosnew:0.0.1-SNAPSHOT
           ports:
            - containerPort: 8082